# Generated by Django 6.0.1 on 2026-02-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='onwer',
            new_name='owner',
        ),
    ]
