# Generated by Django 6.0.1 on 2026-02-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_onwer_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
    ]
